language: ruby
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- jruby-18mode
- jruby-19mode
- rbx
deploy:
  provider: heroku
  api_key:
    secure: BKJZkqT0FArir0M4iFar3pOPPCePscj0opnbdbdDCg05h3g3jJQ1a5dAGA0rQ4JhTIiETIl+CZZMkgMUD2np3PxAl6h10EXGM18Wcc/9gLpDpEwmnSs81cH7/B8d5h4baqXmMBL7nRj4B2Qy5t6s7VpoEB4jHBd4OS27Du/JpKU=
  app: mysterious-atoll-4279
  on:
    repo: brianmc/paymentdemo
